title: Cозданиe 3D-модели территории в QGIS и Qgis2threejs<br>(Часть 1)
description: Это тескт из строки "description" файа «_config.yml»

show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

