title: Моя заметка - Это текст из строки "title" файла «_config.yml»
description: Моя заметка - Это текст из строки "description" файла «_config.yml»

show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

highlighter: rouge
